/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.so.agi;

import ch.interlis.ili2c.Ili2cException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws Ili2cException {
        
        MetaParser parser = new MetaParser();
        parser.doIt("src/test/data/SO_AGI_Modell_Eins_202000513.ili");
        
        
        System.out.println(new App().getGreeting());

    }
}
